# Generated by Django 3.2.12 on 2022-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_addjob_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='Jobtype',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
