# Generated by Django 3.2.12 on 2022-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_addjob_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='prize',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
