# Generated by Django 3.2.12 on 2022-04-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_addjob_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='otpverifywithtimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.EmailField(blank=True, max_length=254, null=True)),
                ('verify', models.BooleanField(default=False)),
            ],
        ),
    ]
