# Generated by Django 3.2.12 on 2022-02-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220205_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduationmrk',
            field=models.ImageField(blank=True, null=True, upload_to='grds'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postgraduationmrk',
            field=models.ImageField(blank=True, null=True, upload_to='postgrds'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenmrk',
            field=models.ImageField(blank=True, null=True, upload_to='ten'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twelvemrk',
            field=models.ImageField(blank=True, null=True, upload_to='twe'),
        ),
    ]
