# Generated by Django 3.2.12 on 2022-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_user_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
