# Generated by Django 3.2.12 on 2022-02-18 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_addjob_prize'),
        ('job', '0011_applyjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobs',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.addjob'),
        ),
        migrations.AlterField(
            model_name='applyjobs',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
