# Generated by Django 3.2.12 on 2022-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20220218_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobs',
            name='verify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
