# Generated by Django 3.2.12 on 2022-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_applyjobs_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='applyjobs',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
