# Generated by Django 3.2.12 on 2022-03-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_applyjobs_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobs',
            name='paid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applyjobs',
            name='paymentid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='SSOkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cpassword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
