# Generated by Django 3.2.12 on 2022-03-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20220302_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobs',
            name='orderid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
