# Generated by Django 3.2.12 on 2022-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_applyjobs_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
