# Generated by Django 3.2.12 on 2022-04-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_auto_20220423_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identity_desc',
            new_name='aadhar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='identity_detail',
            new_name='drivinglicens',
        ),
        migrations.AddField(
            model_name='user',
            name='pancard',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
